const $ = (s, r=document)=>r.querySelector(s);
const $$ = (s, r=document)=>[...r.querySelectorAll(s)];
const storeKey='werkpilot_v01';
const seed={
  users:[
    {u:'admin',p:'1234',name:'المدير',role:'manager'},
    {u:'accountant',p:'1234',name:'المحاسب',role:'accountant'},
    {u:'mechanic',p:'1234',name:'الميكانيكي',role:'mechanic'},
    {u:'warehouse',p:'1234',name:'أمين المستودع',role:'warehouse'}
  ],
  companies:[
    {id:'de',name:'Auto Service',country:'DE',currency:'EUR',docLang:'de'},
    {id:'es',name:'Auto Service España',country:'ES',currency:'EUR',docLang:'es'}
  ],
  customers:[],vehicles:[],repairs:[],estimates:[],invoices:[],purchases:[],inventory:[],employees:[],expenses:[],journal:[],audit:[],settings:{theme:'dark',font:16,uiLang:'ar'}
};
let db=load();
let session=null;
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(storeKey,JSON.stringify(db))}
function id(p='x'){return p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function money(v){return Number(v||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}
function audit(action,detail=''){db.audit.unshift({id:id('a'),ts:new Date().toISOString(),user:session?.user?.name||'system',company:session?.company?.id||'',action,detail});save()}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function roleCan(section){const r=session.user.role;if(r==='manager')return true;if(r==='accountant')return !['profits','settings'].includes(section);if(r==='mechanic')return ['dashboard','customers','vehicles','repairs','integrations'].includes(section);if(r==='warehouse')return ['dashboard','inventory','purchases','integrations'].includes(section);return false}
function login(){document.documentElement.dir='rtl';document.body.innerHTML='';$('#app').innerHTML=`<div id="app"></div>'; class="login-card"><div class="brand">WerkPilot</div><div class="tag">إدارة الورشة الذكية</div><div class="field"><label>اسم المستخدم</label><input id="lu" value="admin"></div><div class="field"><label>كلمة المرور</label><input id="lp" type="password" value="1234"></div><button class="btn primary" id="loginBtn">دخول</button><div class="hint">تجريبي: admin / 1234 · accountant / 1234 · mechanic / 1234 · warehouse / 1234</div></div></div>`;$('#loginBtn').onclick=()=>{const u=db.users.find(x=>x.u===$('#lu').value&&x.p===$('#lp').value);if(!u)return toast('بيانات الدخول غير صحيحة');session={user:u,company:db.companies[0],page:'dashboard'};audit('login');render()}}
const nav=[['dashboard','الرئيسية'],['customers','العملاء'],['vehicles','السيارات'],['repairs','أوامر الإصلاح'],['estimates','Kostenvoranschlag'],['invoices','الفواتير و Barverkauf'],['purchases','المشتريات'],['inventory','المخزون وقطع الغيار'],['employees','الموظفون والرواتب'],['expenses','المصاريف'],['journal','دفتر اليومية'],['reports','التقارير'],['integrations','التكاملات'],['audit','سجل النشاط'],['settings','الإعدادات']];
function render(){document.documentElement.style.setProperty('--font',db.settings.font+'px');const allowed=nav.filter(([k])=>roleCan(k));$('#app').innerHTML=`<div class="shell"><aside class="sidebar" id="side"><div class="sidebrand">WerkPilot</div><div class="nav">${allowed.map(([k,l])=>`<button data-page="${k}" class="${session.page===k?'active':''}">${l}</button>`).join('')}</div></aside><main class="main"><div class="topbar"><div class="top-actions"><button class="btn ghost mobile-menu" id="menu">☰</button><select id="company">${db.companies.map(c=>`<option value="${c.id}" ${c.id===session.company.id?'selected':''}>${c.name} · ${c.country}</option>`).join('')}</select></div><div class="top-actions"><span class="badge hide-mobile"><span class="dot"></span>${session.user.name}</span><button class="btn ghost small" id="logout">خروج</button></div></div><div class="content" id="content"></div></main></div>`;
$$('[data-page]').forEach(b=>b.onclick=()=>{session.page=b.dataset.page;render()});$('#logout').onclick=()=>{audit('logout');session=null;login()};$('#company').onchange=e=>{session.company=db.companies.find(c=>c.id===e.target.value);session.page='dashboard';render()};$('#menu').onclick=()=>$('#side').classList.toggle('open');page()}
function companyRows(name){return db[name].filter(x=>x.companyId===session.company.id)}
function page(){const m={dashboard,customers,vehicles,repairs,estimates,invoices,purchases,inventory,employees,expenses,journal,reports,integrations,audit:auditPage,settings};(m[session.page]||dashboard)()}
function head(title,action=''){return `<div class="page-title"><h1>${title}</h1>${action}</div>`}
function dashboard(){const inv=companyRows('invoices'),exp=companyRows('expenses'),rep=companyRows('repairs'),veh=companyRows('vehicles');const sales=inv.reduce((a,x)=>a+Number(x.total||0),0), costs=exp.reduce((a,x)=>a+Number(x.amount||0),0);$('#content').innerHTML=head('لوحة التحكم')+`<div class="grid"><div class="card"><div class="muted">السيارات</div><div class="metric">${veh.length}</div></div><div class="card"><div class="muted">أوامر الإصلاح المفتوحة</div><div class="metric">${rep.filter(x=>x.status!=='مكتمل').length}</div></div><div class="card"><div class="muted">إجمالي المبيعات</div><div class="metric">${money(sales)}</div></div>${session.user.role==='manager'?`<div class="card"><div class="muted">صافي تقريبي</div><div class="metric">${money(sales-costs)}</div></div>`:''}</div><div class="card" style="margin-top:14px"><div class="kpi-row"><b>الشركة النشطة</b><span class="badge">${session.company.name} · ${session.company.country}</span></div><p class="muted">كل البيانات المعروضة معزولة حسب الشركة النشطة.</p></div>`}
function customers(){const rows=companyRows('customers');$('#content').innerHTML=head('العملاء',`<button class="btn primary" id="add">عميل جديد</button>`)+table(['الاسم','الهاتف','الإيميل','العنوان','السيارات'],rows.map(c=>[c.name,c.phone||'-',c.email||'-',c.address||'-',db.vehicles.filter(v=>v.customerId===c.id).length]));$('#add').onclick=()=>customerModal()}
function customerModal(){modal('عميل جديد',`<div class="form-grid"><div class="field"><label>الاسم</label><input id="n"></div><div class="field"><label>الهاتف</label><input id="ph"></div><div class="field"><label>الإيميل</label><input id="em"></div><div class="field"><label>العنوان</label><input id="ad"></div><div class="field span2"><label>ورقة تسجيل السيارة</label><div class="filebox"><input id="doc" type="file" accept="image/*,.pdf" capture="environment"><div class="muted">كاميرا / استوديو / PDF</div></div></div></div>`,()=>{const c={id:id('c'),companyId:session.company.id,name:$('#n').value.trim(),phone:$('#ph').value,email:$('#em').value,address:$('#ad').value,documentName:$('#doc').files[0]?.name||''};if(!c.name)return toast('أدخل اسم العميل');db.customers.push(c);save();audit('customer.create',c.name);closeModal();render()})}
function vehicles(){const rows=companyRows('vehicles');$('#content').innerHTML=head('السيارات',`<button class="btn primary" id="add">إضافة سيارة</button>`)+table(['العميل','اللوحة','VIN','الماركة','الموديل','السنة','المحرك','اللون'],rows.map(v=>[customerName(v.customerId),v.plate||'-',v.vin||'-',v.make||'-',v.model||'-',v.year||'-',v.engine||'-',v.paint||'-']));$('#add').onclick=vehicleModal}
function vehicleModal(){const customers=companyRows('customers');modal('إضافة سيارة',`<div class="form-grid"><div class="field"><label>العميل</label><select id="cu">${customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><div class="field"><label>رقم اللوحة</label><input id="pl"></div><div class="field"><label>VIN</label><input id="vin"></div><div class="field"><label>الماركة</label><input id="mk"></div><div class="field"><label>الموديل</label><input id="mo"></div><div class="field"><label>السنة</label><input id="yr" type="number"></div><div class="field"><label>كود المحرك</label><input id="en"></div><div class="field"><label>كود اللون</label><input id="pa"></div><div class="field span2"><label>ورقة التسجيل</label><input id="vd" type="file" accept="image/*,.pdf" capture="environment"></div></div>`,()=>{if(!$('#cu').value)return toast('أضف عميلاً أولاً');const v={id:id('v'),companyId:session.company.id,customerId:$('#cu').value,plate:$('#pl').value,vin:$('#vin').value,make:$('#mk').value,model:$('#mo').value,year:$('#yr').value,engine:$('#en').value,paint:$('#pa').value,documentName:$('#vd').files[0]?.name||''};db.vehicles.push(v);save();audit('vehicle.create',v.plate||v.vin);closeModal();render()})}
function repairs(){const rows=companyRows('repairs');$('#content').innerHTML=head('أوامر الإصلاح',`<button class="btn primary" id="add">أمر إصلاح جديد</button>`)+table(['السيارة','الوصف','الفني','الساعات','الحالة'],rows.map(r=>[vehicleName(r.vehicleId),r.description,r.tech||'-',r.hours||0,`<span class="status ${r.status==='مكتمل'?'ok':r.status==='جاري العمل'?'warn':''}">${r.status}</span>`]));$('#add').onclick=repairModal}
function repairModal(){modal('أمر إصلاح جديد',`<div class="form-grid"><div class="field"><label>السيارة</label><select id="rv">${companyRows('vehicles').map(v=>`<option value="${v.id}">${v.plate||v.vin} · ${v.make} ${v.model}</option>`).join('')}</select></div><div class="field"><label>الفني</label><input id="rt"></div><div class="field span2"><label>وصف العطل والعمل</label><textarea id="rd"></textarea></div><div class="field"><label>ساعات العمل</label><input id="rh" type="number" step=".25"></div><div class="field"><label>الحالة</label><select id="rs"><option>جديد</option><option>جاري العمل</option><option>مكتمل</option></select></div></div>`,()=>{const r={id:id('r'),companyId:session.company.id,vehicleId:$('#rv').value,description:$('#rd').value,tech:$('#rt').value,hours:$('#rh').value,status:$('#rs').value};db.repairs.push(r);save();audit('repair.create',r.description);closeModal();render()})}
function estimates(){const rows=companyRows('estimates');$('#content').innerHTML=head('Kostenvoranschlag',`<button class="btn primary" id="add">إنشاء تقدير</button>`)+table(['العميل/السيارة','القطع','الأجور','الخصم','الضريبة','الإجمالي','رسوم التقدير'],rows.map(x=>[vehicleName(x.vehicleId),money(x.parts),money(x.labor),money(x.discount),x.tax+'%',money(x.total),money(x.fee)]));$('#add').onclick=()=>financeModal('estimate')}
function invoices(){const rows=companyRows('invoices');$('#content').innerHTML=head('الفواتير و Barverkauf',`<div class="toolbar"><button class="btn primary" id="inv">فاتورة جديدة</button><button class="btn" id="bar">Barverkauf</button></div>`)+table(['النوع','العميل/السيارة','الصافي','الضريبة','الإجمالي','الدفع'],rows.map(x=>[x.type,vehicleName(x.vehicleId)||'بيع مباشر',money(x.net),x.tax+'%',money(x.total),x.payment||'غير محدد']));$('#inv').onclick=()=>financeModal('invoice');$('#bar').onclick=()=>financeModal('bar')}
function financeModal(type){const title=type==='estimate'?'Kostenvoranschlag':type==='bar'?'Barverkauf':'فاتورة جديدة';modal(title,`<div class="form-grid"><div class="field"><label>السيارة</label><select id="fv"><option value="">بدون سيارة</option>${companyRows('vehicles').map(v=>`<option value="${v.id}">${v.plate||v.vin} · ${v.make} ${v.model}</option>`).join('')}</select></div><div class="field"><label>القطع €</label><input id="fp" type="number" step=".01" value="0"></div><div class="field"><label>الأجور €</label><input id="fl" type="number" step=".01" value="0"></div><div class="field"><label>الخصم €</label><input id="fd" type="number" step=".01" value="0"></div><div class="field"><label>الضريبة %</label><input id="ft" type="number" step=".01" value="19"></div>${type==='estimate'?'<div class="field"><label>رسوم إعداد التقدير €</label><input id="ff" type="number" step=".01" value="0"></div>':'<div class="field"><label>طريقة الدفع</label><select id="pay"><option>غير محدد</option><option>نقدي</option><option>بطاقة</option><option>تحويل بنكي</option></select></div>'}</div>`,()=>{const parts=+$('#fp').value||0,labor=+$('#fl').value||0,discount=+$('#fd').value||0,tax=+$('#ft').value||0,net=Math.max(0,parts+labor-discount),total=net*(1+tax/100);if(type==='estimate'){db.estimates.push({id:id('e'),companyId:session.company.id,vehicleId:$('#fv').value,parts,labor,discount,tax,total,fee:+$('#ff').value||0});audit('estimate.create',money(total))}else{const inv={id:id('i'),companyId:session.company.id,vehicleId:$('#fv').value,type:type==='bar'?'Barverkauf':'Rechnung',parts,labor,discount,tax,net,total,payment:$('#pay').value,date:new Date().toISOString()};db.invoices.push(inv);db.journal.push({id:id('j'),companyId:session.company.id,date:inv.date,type:'مقبوضات',description:inv.type,amount:total});audit('invoice.create',money(total))}save();closeModal();render()})}
function purchases(){const rows=companyRows('purchases');$('#content').innerHTML=head('المشتريات',`<button class="btn primary" id="add">تصوير / تحميل فاتورة شراء</button>`)+table(['المورد','التاريخ','المبلغ','الضريبة','الملف'],rows.map(x=>[x.vendor,x.date,money(x.amount),x.tax+'%',x.file||'-']));$('#add').onclick=()=>modal('فاتورة شراء',`<div class="form-grid"><div class="field"><label>المورد</label><input id="pv"></div><div class="field"><label>التاريخ</label><input id="pd" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>المبلغ €</label><input id="pa" type="number" step=".01"></div><div class="field"><label>الضريبة %</label><input id="pt" type="number" value="19"></div><div class="field span2"><label>الكاميرا / الاستوديو / PDF</label><input id="pf" type="file" accept="image/*,.pdf" capture="environment"></div></div>`,()=>{const x={id:id('p'),companyId:session.company.id,vendor:$('#pv').value,date:$('#pd').value,amount:+$('#pa').value||0,tax:+$('#pt').value||0,file:$('#pf').files[0]?.name||''};db.purchases.push(x);db.expenses.push({id:id('x'),companyId:session.company.id,category:'مشتريات',description:x.vendor,amount:x.amount,date:x.date});db.journal.push({id:id('j'),companyId:session.company.id,date:x.date,type:'مصروفات',description:'شراء · '+x.vendor,amount:x.amount});save();audit('purchase.create',x.vendor);closeModal();render()})}
function inventory(){const rows=companyRows('inventory');$('#content').innerHTML=head('المخزون وقطع الغيار',`<button class="btn primary" id="add">إضافة قطعة</button>`)+table(['رقم OEM','الوصف','المورد','الكمية','الحد الأدنى','شراء','بيع','الحالة'],rows.map(x=>[x.oem,x.name,x.vendor||'-',x.qty,x.min,money(x.buy),money(x.sell),`<span class="status ${+x.qty<=+x.min?'bad':'ok'}">${+x.qty<=+x.min?'منخفض':'متوفر'}</span>`]));$('#add').onclick=()=>modal('إضافة قطعة',`<div class="form-grid"><div class="field"><label>OEM</label><input id="io"></div><div class="field"><label>الوصف</label><input id="in"></div><div class="field"><label>المورد</label><input id="iv"></div><div class="field"><label>الكمية</label><input id="iq" type="number" value="0"></div><div class="field"><label>الحد الأدنى</label><input id="im" type="number" value="1"></div><div class="field"><label>سعر الشراء</label><input id="ib" type="number" step=".01"></div><div class="field"><label>سعر البيع</label><input id="is" type="number" step=".01"></div></div>`,()=>{db.inventory.push({id:id('s'),companyId:session.company.id,oem:$('#io').value,name:$('#in').value,vendor:$('#iv').value,qty:+$('#iq').value,min:+$('#im').value,buy:+$('#ib').value,sell:+$('#is').value});save();audit('inventory.create',$('#io').value);closeModal();render()})}
function employees(){const rows=companyRows('employees');$('#content').innerHTML=head('الموظفون والرواتب',`<button class="btn primary" id="add">إضافة موظف</button>`)+table(['الاسم','الوظيفة','الراتب الصافي','الساعات','صلاحية الأرباح'],rows.map(x=>[x.name,x.role,money(x.salary),x.hours||0,x.profit?'نعم':'لا']));$('#add').onclick=()=>modal('إضافة موظف',`<div class="form-grid"><div class="field"><label>الاسم</label><input id="en"></div><div class="field"><label>الوظيفة</label><select id="er"><option>ميكانيكي</option><option>محاسب</option><option>مستودع</option><option>مدير</option></select></div><div class="field"><label>الراتب الصافي €</label><input id="es" type="number"></div><div class="field"><label>ساعات الشهر</label><input id="eh" type="number" value="0"></div></div>`,()=>{const role=$('#er').value;db.employees.push({id:id('emp'),companyId:session.company.id,name:$('#en').value,role,salary:+$('#es').value,hours:+$('#eh').value,profit:role==='مدير'});save();audit('employee.create',$('#en').value);closeModal();render()})}
function expenses(){const rows=companyRows('expenses');$('#content').innerHTML=head('المصاريف',`<button class="btn primary" id="add">إضافة مصروف</button>`)+table(['التاريخ','الفئة','الوصف','المبلغ'],rows.map(x=>[x.date,x.category,x.description||'-',money(x.amount)]));$('#add').onclick=()=>modal('مصروف جديد',`<div class="form-grid"><div class="field"><label>الفئة</label><select id="xc"><option>إيجار الورشة</option><option>قسط معدات</option><option>بنزين/ديزل</option><option>كهرباء</option><option>إنترنت</option><option>تأمين</option><option>مصروف موظف</option><option>متنوعة</option></select></div><div class="field"><label>المبلغ €</label><input id="xa" type="number" step=".01"></div><div class="field"><label>التاريخ</label><input id="xd" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>الوصف</label><input id="xx"></div></div>`,()=>{const x={id:id('x'),companyId:session.company.id,category:$('#xc').value,amount:+$('#xa').value,date:$('#xd').value,description:$('#xx').value};db.expenses.push(x);db.journal.push({id:id('j'),companyId:session.company.id,date:x.date,type:'مصروفات',description:x.category,amount:x.amount});save();audit('expense.create',x.category);closeModal();render()})}
function journal(){const rows=companyRows('journal').sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#content').innerHTML=head('دفتر اليومية')+table(['التاريخ','النوع','الوصف','المبلغ'],rows.map(x=>[String(x.date).slice(0,10),x.type,x.description,money(x.amount)]))}
function reports(){const inv=companyRows('invoices'),exp=companyRows('expenses');const sales=inv.reduce((a,x)=>a+(+x.total||0),0),cost=exp.reduce((a,x)=>a+(+x.amount||0),0);$('#content').innerHTML=head('التقارير')+`<div class="grid"><div class="card"><div class="muted">المبيعات</div><div class="metric">${money(sales)}</div></div><div class="card"><div class="muted">المصاريف</div><div class="metric">${money(cost)}</div></div><div class="card"><div class="muted">الفواتير</div><div class="metric">${inv.length}</div></div>${session.user.role==='manager'?`<div class="card"><div class="muted">الربح التقريبي</div><div class="metric">${money(sales-cost)}</div></div>`:''}</div><div class="card" style="margin-top:14px"><b>الملف الشهري</b><p class="muted">يجمع فواتير البيع والشراء والمصاريف واليومية للشركة النشطة. تصدير حكومي/ضريبي مباشر غير مفعّل في هذه النسخة التجريبية.</p><button class="btn" id="export">تصدير JSON</button></div>`;$('#export').onclick=()=>{const payload={company:session.company,month:new Date().toISOString().slice(0,7),invoices:inv,purchases:companyRows('purchases'),expenses:exp,journal:companyRows('journal')};download(`WerkPilot-${session.company.country}-${payload.month}.json`,JSON.stringify(payload,null,2))}}
function integrations(){const items=[['PartsLink24','كتالوج OEM حسب الاشتراك المرخّص'],['MATIS','مورد/كتالوج قطع الغيار'],['TSE Germany','تكامل TSE للشركة الألمانية'],['Banking','مطابقة الحركات البنكية والفواتير'],['Vehicle OCR','قراءة ورقة تسجيل السيارة'],['Technical Data','بيانات الإصلاح والمخططات المرخّصة']];$('#content').innerHTML=head('التكاملات')+`<div class="list">${items.map(([n,d])=>`<div class="list-item integration"><div><b>${n}</b><div class="muted">${d}</div></div><span class="status warn">يحتاج إعداد وربط رسمي</span></div>`).join('')}</div>`}
function auditPage(){const rows=db.audit.filter(x=>!x.company||x.company===session.company.id);$('#content').innerHTML=head('سجل النشاط')+table(['الوقت','المستخدم','العملية','التفاصيل'],rows.map(x=>[new Date(x.ts).toLocaleString('de-DE'),x.user,x.action,x.detail]))}
function settings(){if(session.user.role!=='manager'){session.page='dashboard';return render()}$('#content').innerHTML=head('الإعدادات')+`<div class="card"><div class="form-grid"><div class="field"><label>حجم الخط</label><input id="font" type="range" min="14" max="22" value="${db.settings.font}"></div><div class="field"><label>لغة الواجهة</label><select id="lang"><option value="ar">العربية</option><option value="de">Deutsch</option><option value="en">English</option><option value="es">Español</option></select></div></div><div class="actions"><button class="btn primary" id="saveSettings">حفظ</button><button class="btn danger" id="reset">إعادة ضبط البيانات التجريبية</button></div></div>`;$('#lang').value=db.settings.uiLang;$('#saveSettings').onclick=()=>{db.settings.font=+$('#font').value;db.settings.uiLang=$('#lang').value;save();toast('تم الحفظ');render()};$('#reset').onclick=()=>{if(confirm('حذف البيانات المحلية وإعادة النسخة التجريبية؟')){localStorage.removeItem(storeKey);location.reload()}}}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">لا توجد بيانات بعد</td></tr>`}</tbody></table></div>`}
function modal(title,body,onSave){const b=document.createElement('div');b.className='modal-backdrop';b.id='modal';b.innerHTML=`<div class="modal"><h2>${title}</h2>${body}<div class="actions"><button class="btn primary" id="ms">حفظ</button><button class="btn ghost" id="mc">إلغاء</button></div></div>`;document.body.append(b);$('#mc').onclick=closeModal;$('#ms').onclick=onSave;b.onclick=e=>{if(e.target===b)closeModal()}}
function closeModal(){$('#modal')?.remove()}
function customerName(cid){return db.customers.find(c=>c.id===cid)?.name||'-'}
function vehicleName(vid){const v=db.vehicles.find(x=>x.id===vid);return v?`${v.plate||v.vin||''} ${v.make||''} ${v.model||''}`.trim():'-'}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
login();
